// <auto-generated />
namespace Jam3iyati.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migration_9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_9));
        
        string IMigrationMetadata.Id
        {
            get { return "201809220139047_migration_9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
